---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    directory:
      exclude: "kube-prometheus/**/*.json"
      jsonnet:
        libs:
          - vendor
          - kube-prometheus/vendor
      recurse: true
    path: kube-prometheus/
    repoURL: https://github.com/whume/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---