---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    directory:
      exclude: "jsonnetfile.json"
      jsonnet:
        libs:
          - kube-prometheus/vendor
      # recurse: true
    path: kube-prometheus/config
    repoURL: https://github.com/whume/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: kube-prometheus/crds
    repoURL: https://github.com/whume/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true