---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    directory:
      jsonnet:
        libs:
          - vendored
      # recurse: true
    path: examples/continuous-delivery/argocd/kube-prometheus
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---