apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: security
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
      parameters:
        - name: "server.dev.enabled"
          value: "true"
        - name: "server.ingress.enabled"
          value: "true"
        - name: "server.ingress.hosts.host"
          value: ""
        - name: "server.ingress.hosts.paths"
          value: "/vault"
        - name: "injector.enabled"
          value: "false"
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.19.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
