apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  generation: 1
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "Monitoring Stack deployment"
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'